name: ci-python-workflow
on: [push]
jobs:
  check-apllications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python test.py